"""create investigation review events table

Revision ID: 5d6d6a46d37e
Revises: b325bed5f121
Create Date: 2026-08-19 16:20:24.703132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5d6d6a46d37e'
down_revision: Union[str, Sequence[str], None] = 'b325bed5f121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


investigation_report_status = postgresql.ENUM(
    "pending_review",
    "approved",
    "rejected",
    name="investigation_report_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_review_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', investigation_report_status, nullable=False),
    sa.Column('new_status', investigation_report_status, nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=False),
    sa.Column('reviewer_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['investigation_reports.id'], name=op.f('fk_investigation_review_events_report_id_investigation_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_review_events'))
    )
    op.create_index(op.f('ix_investigation_review_events_report_id'), 'investigation_review_events', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_review_events_report_id'), table_name='investigation_review_events')
    op.drop_table('investigation_review_events')
    # ### end Alembic commands ###
