"""create investigation reports table

Revision ID: b325bed5f121
Revises: d3df9123ed9c
Create Date: 2026-08-19 15:45:15.761674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


investigation_report_status = postgresql.ENUM(
    "pending_review",
    "approved",
    "rejected",
    name="investigation_report_status",
    create_type=False,
)


# revision identifiers, used by Alembic.
revision: str = 'b325bed5f121'
down_revision: Union[str, Sequence[str], None] = 'd3df9123ed9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    investigation_report_status.create(
        op.get_bind(),
        checkfirst=True,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('citation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', investigation_report_status, server_default='pending_review', nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewer_feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_investigation_reports_confidence_range')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_investigation_reports_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_reports')),
    sa.UniqueConstraint('job_id', name=op.f('uq_investigation_reports_job_id'))
    )
    op.create_index(op.f('ix_investigation_reports_incident_id'), 'investigation_reports', ['incident_id'], unique=False)
    op.create_index(op.f('ix_investigation_reports_status'), 'investigation_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_reports_status'), table_name='investigation_reports')
    op.drop_index(op.f('ix_investigation_reports_incident_id'), table_name='investigation_reports')
    op.drop_table('investigation_reports')
    # ### end Alembic commands ###

    investigation_report_status.drop(
        op.get_bind(),
        checkfirst=True,
    )
